/* Generated By:JavaCC: Do not edit this line. GcodereaderConstants.java */
package org.roiderh.gcodeviewer.lexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GcodereaderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LABEL = 5;
  /** RegularExpression Id. */
  int STARTPARAM = 6;
  /** RegularExpression Id. */
  int PARAM = 7;
  /** RegularExpression Id. */
  int TEXT = 8;
  /** RegularExpression Id. */
  int G = 9;
  /** RegularExpression Id. */
  int SHORT_PARAM = 10;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 11;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 12;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_PARAM = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<LABEL>",
    "<STARTPARAM>",
    "<PARAM>",
    "<TEXT>",
    "<G>",
    "<SHORT_PARAM>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
  };

}
